run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - prealloc

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/imamik/polaroid-image-modifier
  misspell:
    locale: US
  gosec:
    excludes:
      - G404

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
